### ISSUE TITLE
Bundled JSON files with top level arrays converted to objects

### ISSUE THREAD

**Issue by Hypercubed** [systemjs/plugin-json#12]
Quick demo of the bug here:

https://github.com/Hypercubed/plugin-json-bug

In dev the output is:

```
arr [1,2,3]
```

using the bundle the array is converted to an object.

```
arr {0: 1, 1: 2, 2: 3}
```

**Comment by Hypercubed** [comment]
Possible fix:  https://github.com/Hypercubed/plugin-json/blob/fix/array-json/json.js#L8

**Comment by guybedford** [comment]
That looks good to me, PR welcome!
