### ISSUE TITLE
Convert to commonjs format

### ISSUE THREAD

**Issue by unional** [systemjs/plugin-json#15]
I'm working on the plugin system as described in https://github.com/systemjs/systemjs/issues/1528

It is progressing well. 😏 

One issue arise is to load the `package.json` or any resources in the plugin that requires a loader.

Using `package.json` as an example, the host `SystemJS` needs to use the `json.js` loader.

However, I don't want require the host to define and rely on `systemjs.config.js` (or `jspm` with `jspm.config.js` for that matter) and let `SystemJS` to load the config and subsequently load the loader dynamically.

I use `SystemJS.set('json.js', SystemJS.newModule(jsonLoader))` to pre-load and register the loader.

I have tested and it is working, however I have to convert the `json.js` in this repo to commonjs format so that I can use it directly in the code.

If I don't, it will fail as `define()` is not defined in NodeJS.

Since this repo is published as `systemjs-plugin-json` in `npm`, we should be able to load it in NodeJS. 😛 

Here is the converted code (written in TypeScript without any type. 😜 ):

```ts
// this code allows named exports of valid identifiers in json to work with rollup
// so you can effectively "pick" a json value and have the other base-level json values excluded
// not comprehensive of course
function isValidIdentifier(exportName) {
  return exportName.match(/^[a-zA-Z_$][0-9a-zA-Z_$]*$/);
}

export const jsonLoader = {
  translate: function (load) {
    const json = JSON.parse(load.source);
    if (this.builder && this.transpiler && !Array.isArray(json)) {
      load.metadata.format = 'esm';

      const namedExports = Object.keys(json);
      const validIdentifiers = namedExports.filter(isValidIdentifier);

      const output = ['exp' + 'ort var __useDefault = true;\n'];

      validIdentifiers.forEach(function (exportName) {
        output.push('exp' + 'ort var ' + exportName + ' = ' + JSON.stringify(json[exportName]) + ';\n');
      });

      output.push('exp' + 'ort default {\n');
      namedExports.forEach(function (exportName) {
        if (validIdentifiers.indexOf(exportName) !== -1) {
          output.push(exportName + ': ' + exportName + ',\n');
        }
        else {
          output.push(JSON.stringify(exportName) + ': ' + JSON.stringify(json[exportName]) + ',\n');
        }
      });

      output.push('};');

      return output.join('');
    }
    if (this.builder) {
      load.metadata.format = 'cjs';
      return 'module.exports = ' + JSON.stringify(json);
    }
  },
  instantiate: function (load) {
    if (!this.builder) {
      return JSON.parse(load.source);
    }
  }
}
```

**Comment by unional** [comment]
I can create a PR for it if that's ok.

**Comment by guybedford** [comment]
Changing the module format here would be a breaking change, so we'd have to post a new major, but I'd be open to supporting this if you want to post a PR. I'd prefer to stick to plain CommonJS over a TypeScript build step for this project though.

**Comment by unional** [comment]
> I'd prefer to stick to plain CommonJS over a TypeScript build step for this project though.

Yes of course. Will be in plain CommonJS. Doing it now. 🌷

**Comment by unional** [comment]
> written in TypeScript without any type. 😜

is actually a joke because TypeScript without any type is JavaScript. 😛
