### ISSUE TITLE
Please configure package.json and register this as npm package.

### ISSUE THREAD

**Issue by kburson** [systemjs/plugin-json#2]
The projects that I am working on are moving away from bower and attempting to reliy entirely on npm for external dependencies.  This is prefaced by the AngularJS team moving their stuff to the npm registry.

Please make this an npm package and register it so we can make use of it from npm and not bower.

Thank you

**Comment by kresli** [comment]
+1

**Comment by jadrake75** [comment]
+1

**Comment by therealklanni** [comment]
Looks like the package.json was updated, but this was never published. @guybedford?

**Comment by mntnoe** [comment]
I have worked around this until now by refering directly to the git repo in package.json:

```
"dependencies": {
  ...
  "systemjs-plugin-json": "git://github.com/systemjs/plugin-json.git",
  ...
}
```

**Comment by arcanis** [comment]
Ping @guybedford ?

**Comment by guybedford** [comment]
@arcanis sure I've published it to npm.

**Comment by arcanis** [comment]
Great, thanks ! :+1:
