### ISSUE TITLE
importing the json loader causes execution to fail silently!

### ISSUE THREAD

**Issue by CxRes** [systemjs/plugin-json#20]
I think this is a bug but may be I am wrong?? If I do something like: 
```
import 'json'
```
the page loading (systemjs loading import file) stops somewhere in between and there is no error message. I once waited really long to get a timeout but have not been able to reproduce this. I don't know what other helpful information I can provide...

I already import `css` and `html` like this without problems. The reason I am doing this is that I want to keep some json files outside the bundle which the user can configure by hand before loading the page (I am using nwjs, so the user has access to the files). 

JSPM 0.16.53

**Comment by guybedford** [comment]
Odd, SystemJS 0.19 did have some unfixed race conditions in the pipeline, so this may somehow be triggering one of those. Unfortunately I'm no longer personally maintaining SystemJS 0.19, so while I know it's highly inadequate, I'd suggest trying to find a loading order that can work for you here.

**Comment by CxRes** [comment]
:(, But Thanks for letting me know!!!!!!!! At least I know that I am not making a mistake.

I have found a way around it by loading a dummy json for now but it is not a good solution in the long run. 

I am reluctant to upgrade to jspm 0.17 immediately (maybe in a next few months or perhaps when you can reach a RC), as I otherwise functional code which I am reluctant to disturb.

One request that I have (which is much to ask when one is already getting a free lunch) is to see if you can please provide good documentation on best way to deal with breaking-changes when you do come to the RC. For example, it is unclear (at least to me) if there are different strategies to deal with depreciated path wildcards other than explicit listing or how to map paths and deal with overrides in multi-repo setups in 0.17/0.20.
