### ISSUE TITLE
systemjs-plugin-json cause infinity loading

### ISSUE THREAD

**Issue by lexon0011** [systemjs/plugin-json#21]
I require a way to load *.json via SystemJS. For this I add the following lines to my systemjs config:

```
System.config({ 
   'meta': { 
      '*.json': { loader: 'systemjs-plugin-json' } 
   },
   'path': {
      'app': 'app',
      'systemjs-plugin-json': 'node_modules/systemjs-plugin-json/json.js',
   }
});
```

Without the statement `"meta": { '*.json': { loader: 'systemjs-plugin-json' } }` everything works fine, but after adding this line the webapplication runs into a infinity loop (browser doesn't complete loading, the application allocate a lot of memory).

Here I add the full config: [systemjs.config.lineAndIngest.zip](https://github.com/systemjs/plugin-json/files/1146149/systemjs.config.lineAndIngest.zip)

Could anyone help me with this problem?

Thanks!

**Comment by guybedford** [comment]
Try and restrict the json wildcard to just your application path - `'meta': { './lib/*.json': {...} }`.

**Comment by lexon0011** [comment]
Thank you very much, now it works!
