### ISSUE TITLE
Installation failure?

### ISSUE THREAD

**Issue by geelen** [systemjs/plugin-json#4]
Just starting a new project tonight, this happened:

![image](https://cloud.githubusercontent.com/assets/23264/7338638/ec329418-ec52-11e4-8a43-3dbb0091105d.png)

Don't have time to follow it down right now, but didn't want to leave it unreported either. Can look into it further if you need me to.

**Comment by guybedford** [comment]
Thanks - yes this was an unfortunate install bug, fixed in 0.15.5.
