### ISSUE TITLE
.js extension is added when loading json file

### ISSUE THREAD

**Issue by naz** [systemjs/plugin-json#5]
While trying to load a file like so: `import myJson from '/test/mocks/my-json!json';` or like so: `import myJson from '/test/mocks/my-json.json';` The loader is adding the `.js` extension in the end of request while doing import. Wha I get form phantom in the concole is something like this:

```
Error loading http://localhost:9877/test/mocks/my-json.json.js as "/test/mocks/my-json.json" 
```

Currently using: `"json": "github:systemjs/plugin-json@0.1.0",` with jspm version `0.16.14`.

Is there anything I'm missing? Thanks!

**Comment by guybedford** [comment]
`import myJson from '/test/mocks/my-json!json'` should certainly not add the `.js` extension. For the other case it would depend on how you are configuring the plugin.

Are you following https://github.com/systemjs/systemjs/blob/master/docs/overview.md#basic-use here and using the latest version of SystemJS?
