### ISSUE TITLE
Error: fatal: unable to access 'systemjs/plugin-json.git

### ISSUE THREAD

**Issue by nillis** [systemjs/plugin-json#7]
@guybedford when updating plugin-json through jspm update, an error occurs, due a corrupt release. When trying to download the zip through the Github site, you get an 502
https://codeload.github.com/systemjs/plugin-json/zip/0.1.1

![image](https://cloud.githubusercontent.com/assets/2675228/14787041/030a41da-0b02-11e6-8674-8d4193b3b8df.png)

**Comment by nillis** [comment]
Also happen to 0.1.0. The zip's seem to be not available causing jspm to crash on it.

**Comment by jutxle** [comment]
Encountering the same issues

**Comment by nillis** [comment]
Switching to npm version seems to be working. Altough core-js has a dependency on the github version.

**Comment by wzhao-c** [comment]
```
warn Error on lookup for github:systemjs/plugin-json, retrying (1).
     Error: fatal: Could not read from remote repository.

     Please make sure you have the correct access rights
     and the repository exists.
```

**Comment by tthai-cengage** [comment]
seeing the same issue as well

**Comment by matthewcarlino** [comment]
Seems not to be limited to jspm.  A simple git clone fails as well...

```
PS C:\workspace\sysjs> git clone https://github.com/systemjs/plugin-json.git
Cloning into 'plugin-json'...
fatal: unable to access 'https://github.com/systemjs/plugin-json.git/': transfer closed with outstanding read data remaining
```

**Comment by alexisvincent** [comment]
@guybedford  same here

**Comment by grady-lad** [comment]
Also experiencing this issue ....

**Comment by AStoker** [comment]
@nillis, how did you change the dependency? I'm trying to override it in the package.json, but running jspm install gets an error saying that my override is not a valid dependency format for npm

**Comment by NicholasGWK** [comment]
It seems like as a temporary workaround a forked repo will work. Not saying we all should, but I did and pointed my config.js to NicholasGWK/plugin-json and that seems to work. Seems like it's legitimately an access problem.

**Comment by vic0nt** [comment]
+1

**Comment by grady-lad** [comment]
my quick work around suggestion is to run a jspm install and let it fail and then do a find and replace of instance of 'github:systemjs/plugin-json@0.1.0' and replace it with 'npm:systemjs-plugin-json@0.1.0'. I am just doing this as I am completely blocked in work...

**Comment by jlamontagne** [comment]
@AStoker Try changing instances of "github:systemjs/plugin-json@0.1.0" to "npm:systemjs-plugin-json@0.1.0" in your package.json and JSPM config. (Sorry @nillis, meant to tag @AStoker earlier. :))

**Comment by nillis** [comment]
@jlamontagne idd I know that would solve the problem, although in a production environment I would prefer not to be dependent on Github. So for the long term looking for a "Github proxy" server solution.
Else I would prefer to checking in jspm_packages into source control and performing a "jspm install -q" on CI to be undependent of remote package sources.

**Comment by PacciniBruno** [comment]
Doing a single commit (updating the README.md for example) worked for me on my fork (which was also broken for some reason... It existed prior to the issue, that might be why).
Only way to do it was to make the edit on github's interface, since I couldn't pull/push anymore on my own repo...  Definitely weird

**Comment by GiedriusGrabauskas** [comment]
Same here...

**Comment by danielabar** [comment]
Does anyone know how to fix this if not depending on systemjs/plugin-json directly, but it appears several times in config.js as transitive dep, for example, just a few entries from my config.json:

```
   "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-js@2.2.2": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
```

I tried the earlier suggestion about replacing all github plugin-json references with the npm one, but it still fails when running `jspm install <a new dep>`

**Comment by AStoker** [comment]
As if by magic, running it again suddenly works.

**Comment by guybedford** [comment]
I tried tagging a 0.1.2, let me know if that helps.

**Comment by AStoker** [comment]
@guybedford it seems to work now.

**Comment by nillis** [comment]
@guybedford great, it works! Any suggestions on my last post? Do you know of any proxy/caching solution for Github as there exists for npm (https://github.com/rlidwka/sinopia)?

**Comment by jbreckmckye** [comment]
But why has it started working all of a sudden?

![Mysterious...](http://i.imgur.com/o0T4zZU.jpg?1)

**Comment by PacciniBruno** [comment]
For the record (ten thousand years later), I contacted github support at the time. They confirmed it was a github server issue: 

"The problem was on GitHub's side.  We had a problem on one server, which broke both clones and pushes for a limited number of repositories.  All forks of a given repository would be affected together, which is why both systemjs/plugin-json and your fork of it were down at the same time.

We fixed the problem on our side, so your repo and the public one should both be fine now.  Sorry for the inconvenience, and please let us know if you have any further difficulties.

--Patrick"

**Comment by jperals** [comment]
Close?
